Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/10/2019
Var
// Seção de Declarações das variáveis 
   contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   contador <- 10
   enquanto (contador>=0)faca
           escreval(contador)
           contador <- contador-2
   fimenquanto
   escreva("Terminei de contar!!!")

Fimalgoritmo