Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/10/2019
Var
// Seção de Declarações das variáveis 
   reais, dolares:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Quantos reais eu tenho? R$ ")
   leia (reais)
   dolares <- reais/2.20
   escreva("Eu tenho US$ ",dolares:4:2)

Fimalgoritmo