Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/10/2019
Var
// Seção de Declarações das variáveis 
   preco, imposto:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Qual o preco do produto? US$ ")
   leia (preco)
   imposto <- (preco*60)/100
   escreva("O preco do imposto sera de US$ ",imposto:5:2)
   
   
Fimalgoritmo