Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/10/2019
Var
// Seção de Declarações das variáveis 
    n:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um numero: ")
   leia (n)
   se (n%2=0)entao
      escreval("O numero e",n," e par")
   senao
      escreval("O numeror e",n," e impar")
   fimse
   

Fimalgoritmo