Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/10/2019
Var
// Seção de Declarações das variáveis 
   f, c: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Qual a temperatura aqui? ")
   leia (f)
   c <- (f-32)/1.8
   escreva("A temperatura no Brasil e ",c:4:1)
Fimalgoritmo